[package]
name = "rust-actix-pg"
version = "0.1.0"
edition = "2021"

[dependencies]
actix="0.13.0"
actix-web="4.3.1"
dotenv="0.15.0"
serde = {version="1.0.152", features=["derive"]}
serde_json="1.0.93"
sqlx = { version = "0.8.2", features = ["runtime-async-std-native-tls", "postgres"] }